apiVersion: v1
description: A Helm chart for Logz.io fluentd
name: logzio-fluentd-helm
appVersion: 1.1.0
version: 1.0.0
keywords:
  - logging
  - logz.io
  - fluentd
icon: https://avatars1.githubusercontent.com/u/7902073?s=200&v=4
