{{- if .Values.apiAccessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: logzio-logs-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  logzio-log-shipping-token: {{ .Values.apiAccessToken | b64enc | quote }}
  logzio-log-listener: {{ .Values.apiListener | b64enc | quote }}
{{- end }}
